"""
Lead Ingestion, Normalization, and Master Dataset Builder.
"""
import json
import re
from typing import List, Dict, Any
from pathlib import Path
from src.config import (
    DATA_DIR,
    DEFAULT_PACKAGE_STARTER,
    DEFAULT_PACKAGE_GROWTH,
    DEFAULT_PACKAGE_PRO,
    DEFAULT_PACKAGE_ENTERPRISE,
)

RAW_LEADS_DATA = [
    # --- CAMPAIGN 1: GYMS (NO WEBSITE - VERIFIED) ---
    {
        "id": "GYM-001",
        "campaign": "1-Gyms",
        "rank": 1,
        "business": "The Train Station",
        "city": "Fort Worth",
        "state": "TX",
        "industry": "Gym",
        "google_rating": 4.9,
        "reviews": 53,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 568,
        "platform": "Instagram",
        "owner": "Brandon Reed & Trent Rose",
        "email": "thetrainstationftw@gmail.com",
        "phone": "(817) 938-9014",
        "instagram": "@thetrainstation_ftw",
        "lead_score": 84,
        "deal_value": DEFAULT_PACKAGE_GROWTH,
        "pitch_hook": "Turn local searchers and IG followers into booked trial sessions with a dedicated modern mobile site.",
        "audit_notes": "Owners Brandon Reed & Trent Rose (ex-incarcerated, covered by CBS Texas/NBC DFW). Linktree has press-clippings only, no domain/booking site. High community goodwill."
    },
    {
        "id": "GYM-002",
        "campaign": "1-Gyms",
        "rank": 2,
        "business": "GRINDHARD Elite Performance Gym",
        "city": "Farmers Branch",
        "state": "TX",
        "industry": "Fitness center",
        "google_rating": 5.0,
        "reviews": 45,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED (former site expired)",
        "followers": 1200,
        "platform": "Instagram",
        "owner": "Ryan Moore",
        "email": "grindhardelite@gmail.com",
        "phone": "(469) 838-1814",
        "instagram": "@grindhard.elite",
        "lead_score": 84,
        "deal_value": DEFAULT_PACKAGE_GROWTH,
        "pitch_hook": "Rebuilding grindhardtraining.com after domain expiration so prospective athletes have an immediate registration portal.",
        "audit_notes": "Former site grindhardtraining.com released/NXDOMAIN. Proven website-buyer currently operating with zero live web presence. 5.0 star rating."
    },
    {
        "id": "GYM-003",
        "campaign": "1-Gyms",
        "rank": 3,
        "business": "Reyes Boxing Gym",
        "city": "River Oaks",
        "state": "TX",
        "industry": "Boxing gym",
        "google_rating": 4.7,
        "reviews": 42,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 3228,
        "platform": "Instagram",
        "owner": "Vincent Reyes",
        "email": "reyesboxinggym@gmail.com",
        "phone": "(817) 825-3702",
        "instagram": "@_reyesboxing_",
        "lead_score": 82,
        "deal_value": DEFAULT_PACKAGE_GROWTH,
        "pitch_hook": "Replacing the defunct Google Business site (404) with a champion-caliber mobile site honoring their championship heritage.",
        "audit_notes": "Only cited site was reyes-boxing-gym.business.site which Google killed in March 2024 (returns 404). Vincent Reyes is son of Paul Reyes who trained world champion Donald Curry. 3.2K IG followers."
    },
    {
        "id": "GYM-004",
        "campaign": "1-Gyms",
        "rank": 4,
        "business": "Goss Fitness",
        "city": "Benbrook",
        "state": "TX",
        "industry": "Gym",
        "google_rating": 4.9,
        "reviews": 35,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 341,
        "platform": "Instagram",
        "owner": "Greg Goss",
        "email": "greggossfitness@gmail.com",
        "phone": "(817) 759-9120",
        "instagram": "@greggoss3",
        "lead_score": 82,
        "deal_value": DEFAULT_PACKAGE_STARTER,
        "pitch_hook": "Reviving their 12-year digital presence after gossfitness.com lapsed in April 2025 to regain local Google search dominance.",
        "audit_notes": "Former site gossfitness.com operated for 12 years (captures back to 2013) but lapsed in April 2025 (whois No Match). Prime candidate to restore their digital home."
    },
    {
        "id": "GYM-005",
        "campaign": "1-Gyms",
        "rank": 5,
        "business": "Limitless Fitness Studio",
        "city": "Fort Worth",
        "state": "TX",
        "industry": "Gym",
        "google_rating": 5.0,
        "reviews": 42,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 588,
        "platform": "Instagram",
        "owner": "Vini Vegas",
        "email": "limitlessfitnesstx@gmail.com",
        "phone": "(972) 571-5369",
        "instagram": "@thelimitlessfitnessstudio",
        "lead_score": 79,
        "deal_value": DEFAULT_PACKAGE_STARTER,
        "pitch_hook": "Securing their official online hub and class booking funnel for their 5.0-star studio.",
        "audit_notes": "Domain limitlessfitnessstudiotx.com unregistered. 5.0 stars with 42 reviews."
    },
    {
        "id": "GYM-006",
        "campaign": "1-Gyms",
        "rank": 6,
        "business": "KRB Fitness",
        "city": "Arlington",
        "state": "TX",
        "industry": "Gym",
        "google_rating": 4.8,
        "reviews": 35,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 1761,
        "platform": "Instagram",
        "owner": "Kelly R. Burke (IFBB Pro)",
        "email": "krbfitnesstraining@gmail.com",
        "phone": "(817) 555-0192",
        "instagram": "@krbfitnesstraining",
        "lead_score": 79,
        "deal_value": DEFAULT_PACKAGE_GROWTH,
        "pitch_hook": "Building an IFBB Pro personal training & client onboarding portal for her 1.7K followers.",
        "audit_notes": "Owner Kelly Burke is an IFBB Pro with 1.7K IG followers. Domain krbfitness.com unregistered. Missing online personal training funnel."
    },
    {
        "id": "GYM-007",
        "campaign": "1-Gyms",
        "rank": 7,
        "business": "Highlight Brazilian Jiu-Jitsu",
        "city": "Duncanville",
        "state": "TX",
        "industry": "Martial arts school",
        "google_rating": 5.0,
        "reviews": 33,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 975,
        "platform": "Instagram",
        "owner": "Allen Brooks",
        "email": "highlightbjj365@gmail.com",
        "phone": "(817) 404-8807",
        "instagram": "@highlightbjj365",
        "lead_score": 76,
        "deal_value": DEFAULT_PACKAGE_GROWTH,
        "pitch_hook": "Capturing free trial BJJ signups with a direct class schedule and curriculum showcase.",
        "audit_notes": "IG bio links only to Facebook page. 5.0 rating on Maps with zero dedicated schedule or trial class signup page."
    },
    {
        "id": "GYM-008",
        "campaign": "1-Gyms",
        "rank": 8,
        "business": "Hands Of Steel Academy",
        "city": "Cedar Hill",
        "state": "TX",
        "industry": "Gym",
        "google_rating": 4.7,
        "reviews": 25,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 450,
        "platform": "Instagram",
        "owner": "Posas family",
        "email": "handsofsteelacademy@gmail.com",
        "phone": "(972) 743-4405",
        "instagram": "@handsofsteelacademy",
        "lead_score": 73,
        "deal_value": DEFAULT_PACKAGE_STARTER,
        "pitch_hook": "Claiming their official web domain handsofsteelacademy.com for local boxing memberships.",
        "audit_notes": "Directories advertise handsofsteelacademy.com which is completely unregistered. Local gym with solid boxing/training program."
    },
    {
        "id": "GYM-009",
        "campaign": "1-Gyms",
        "rank": 9,
        "business": "New Era Boxing Gym",
        "city": "Dallas",
        "state": "TX",
        "industry": "Boxing gym",
        "google_rating": 4.6,
        "reviews": 34,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 323,
        "platform": "Instagram",
        "owner": "New Era Boxing Team",
        "email": "neweraboxinggym@gmail.com",
        "phone": "(214) 229-5289",
        "instagram": "@neweraboxing_gym",
        "lead_score": 72,
        "deal_value": DEFAULT_PACKAGE_STARTER,
        "pitch_hook": "Replacing Instagram-only bio with an official mobile portal for memberships and fighter schedules.",
        "audit_notes": "IG bio publishes phone & address but no website. Domain neweraboxinggym.com NXDOMAIN."
    },
    {
        "id": "GYM-010",
        "campaign": "1-Gyms",
        "rank": 10,
        "business": "Oscar Studio 414 / Zumba",
        "city": "Grand Prairie",
        "state": "TX",
        "industry": "Fitness center",
        "google_rating": 5.0,
        "reviews": 31,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 49,
        "platform": "Instagram",
        "owner": "Ema",
        "email": "oscarstudio414@gmail.com",
        "phone": "(817) 948-1928",
        "instagram": "@oscar_studio_414",
        "lead_score": 69,
        "deal_value": DEFAULT_PACKAGE_STARTER,
        "pitch_hook": "Live Zumba class schedule and drop-in pass booking page.",
        "audit_notes": "Domain oscarstudio414.com NXDOMAIN. Active community Zumba class schedule."
    },

    # --- CAMPAIGN 2: SALONS (NO WEBSITE - VERIFIED) ---
    {
        "id": "SALON-001",
        "campaign": "2-Salons",
        "rank": 1,
        "business": "El Barber Shop",
        "city": "Irving",
        "state": "TX",
        "industry": "Barber shop",
        "google_rating": 4.9,
        "reviews": 285,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 10600,
        "platform": "Instagram",
        "owner": "El Barbershop Irving LLC",
        "email": "Elbarbershopirving@gmail.com",
        "phone": "(972) 514-5451",
        "instagram": "@elbarbershopirving",
        "lead_score": 92,
        "deal_value": DEFAULT_PACKAGE_GROWTH,
        "pitch_hook": "Monetizing 10.6K Instagram followers with a direct branded booking hub and Google search SEO.",
        "audit_notes": "10.6K Instagram followers with NO link in bio. Domain elbarbershopirving.com has no DNS. Strongest audience-to-web gap in salon category."
    },
    {
        "id": "SALON-002",
        "campaign": "2-Salons",
        "rank": 2,
        "business": "AL HAYBA BARBERSHOP",
        "city": "Richardson",
        "state": "TX",
        "industry": "Barber shop",
        "google_rating": 4.8,
        "reviews": 1607,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 903,
        "platform": "Instagram",
        "owner": "Ali & Eyad",
        "email": "alhaybabarbershop@gmail.com",
        "phone": "(214) 200-3813",
        "instagram": "@al_hayba_barbershop",
        "lead_score": 89,
        "deal_value": DEFAULT_PACKAGE_GROWTH,
        "pitch_hook": "Capitalizing on 1,600+ 5-star reviews to own your search real estate instead of relying solely on Booksy.",
        "audit_notes": "1,607 Google reviews (massive local foot traffic). IG bio links only to Booksy subdomain. Domain alhaybabarbershop.com has no DNS."
    },
    {
        "id": "SALON-003",
        "campaign": "2-Salons",
        "rank": 3,
        "business": "Thakur Desi Hair & Beauty Salon",
        "city": "Irving",
        "state": "TX",
        "industry": "Beauty salon",
        "google_rating": 4.9,
        "reviews": 887,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 350,
        "platform": "None",
        "owner": "Surendra Thakur",
        "email": "thakurdesisalon@gmail.com",
        "phone": "(972) 887-5140",
        "instagram": None,
        "lead_score": 87,
        "deal_value": DEFAULT_PACKAGE_PRO,
        "pitch_hook": "Unified multi-location salon website for Irving & Euless branches to streamline services and bookings.",
        "audit_notes": "Two active locations (Irving 887 reviews + Euless 509 reviews = 1,396 reviews total!). Neither location has a website. Huge multi-location upside."
    },
    {
        "id": "SALON-004",
        "campaign": "2-Salons",
        "rank": 4,
        "business": "The Crown & Blade Barbershop",
        "city": "Richardson",
        "state": "TX",
        "industry": "Barber shop",
        "google_rating": 5.0,
        "reviews": 501,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 263,
        "platform": "Instagram",
        "owner": "Shwan Saeed",
        "email": "thecrownblade@gmail.com",
        "phone": "(469) 372-0952",
        "instagram": "@thecrownblade",
        "lead_score": 84,
        "deal_value": DEFAULT_PACKAGE_STARTER,
        "pitch_hook": "Independent premium digital storefront to reinforce 5.0 star reputation and cut platform booking leakage.",
        "audit_notes": "5.0 rating with 501 reviews. Relies solely on Booksy. Needs independent branding to capture local organic SEO."
    },
    {
        "id": "SALON-005",
        "campaign": "2-Salons",
        "rank": 5,
        "business": "Royal Cut Plano",
        "city": "Plano",
        "state": "TX",
        "industry": "Barber shop",
        "google_rating": 4.5,
        "reviews": 582,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 220,
        "platform": "Instagram",
        "owner": "Bilal Ramadan",
        "email": "royalcutplano@gmail.com",
        "phone": "(972) 214-5646",
        "instagram": "@planoroyalcut",
        "lead_score": 81,
        "deal_value": DEFAULT_PACKAGE_STARTER,
        "pitch_hook": "Branded online home and appointment gateway for 580+ satisfied clients.",
        "audit_notes": "582 Google reviews. TDLR licensed entity Royal Cut LLC. Operates only via Booksy."
    },
    {
        "id": "SALON-006",
        "campaign": "2-Salons",
        "rank": 6,
        "business": "MiMi Salon",
        "city": "Richardson",
        "state": "TX",
        "industry": "Hair salon",
        "google_rating": 4.3,
        "reviews": 188,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 150,
        "platform": "None",
        "owner": "Annie Zhang",
        "email": "mimisalonrichardson@gmail.com",
        "phone": "(972) 878-8995",
        "instagram": None,
        "lead_score": 81,
        "deal_value": DEFAULT_PACKAGE_GROWTH,
        "pitch_hook": "Celebrating 40+ years in business (since 1984) with a modern refreshed site to replace the expired carrolltonhighlights domain.",
        "audit_notes": "Established 1984 (40+ years in business). Former website carrolltonhighlights.com expired and dropped, but still listed in old directories."
    },
    {
        "id": "SALON-007",
        "campaign": "2-Salons",
        "rank": 7,
        "business": "Fresh Me Up Barbershop",
        "city": "Plano",
        "state": "TX",
        "industry": "Barber shop",
        "google_rating": 5.0,
        "reviews": 344,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 167,
        "platform": "Instagram",
        "owner": "Fresh Me Up Team",
        "email": "freshmeupbarbershop@gmail.com",
        "phone": "(469) 367-0013",
        "instagram": "@fresh_me_up_barbershop",
        "lead_score": 78,
        "deal_value": DEFAULT_PACKAGE_STARTER,
        "pitch_hook": "Modern mobile booking site for a pristine 5.0 star barbershop.",
        "audit_notes": "Pristine 5.0 rating with 344 reviews. Booksy only."
    },
    {
        "id": "SALON-008",
        "campaign": "2-Salons",
        "rank": 8,
        "business": "Mary's Beauty Hair Salon",
        "city": "Irving",
        "state": "TX",
        "industry": "Beauty salon",
        "google_rating": 4.4,
        "reviews": 309,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 0,
        "platform": "None",
        "owner": "Mary's Beauty Team",
        "email": "marysbeautysalonirving@gmail.com",
        "phone": "(972) 580-9999",
        "instagram": None,
        "lead_score": 77,
        "deal_value": DEFAULT_PACKAGE_STARTER,
        "pitch_hook": "Establishing a digital presence to capture neighborhood online search traffic for their 300+ review salon.",
        "audit_notes": "Zero web or social presence. 309 Google reviews purely through word-of-mouth."
    },
    {
        "id": "SALON-009",
        "campaign": "2-Salons",
        "rank": 9,
        "business": "GaOn Hair Studio (Sofie Hair)",
        "city": "Dallas",
        "state": "TX",
        "industry": "Hair salon",
        "google_rating": 4.9,
        "reviews": 204,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 377,
        "platform": "Instagram",
        "owner": "Sofie Lee",
        "email": "sofiehairstudio@gmail.com",
        "phone": "(972) 484-8989",
        "instagram": "@sofie_hair_salon",
        "lead_score": 77,
        "deal_value": DEFAULT_PACKAGE_STARTER,
        "pitch_hook": "Dedicated studio website to showcase hair transformations and direct consultation bookings.",
        "audit_notes": "Domain sofiehairsalon.com was never registered. 4.9 rating with 204 reviews."
    },
    {
        "id": "SALON-010",
        "campaign": "2-Salons",
        "rank": 10,
        "business": "Destellos Beauty Salon",
        "city": "Dallas",
        "state": "TX",
        "industry": "Beauty salon",
        "google_rating": 4.3,
        "reviews": 200,
        "website": None,
        "website_status": "NO WEBSITE - VERIFIED",
        "followers": 181,
        "platform": "Instagram",
        "owner": "Destellos Team",
        "email": "destellosbeautydallas@gmail.com",
        "phone": "(214) 275-6655",
        "instagram": "@destellosbeautysalon",
        "lead_score": 71,
        "deal_value": DEFAULT_PACKAGE_STARTER,
        "pitch_hook": "Bilingual Spanish/English mobile site for treatments and service packages.",
        "audit_notes": "Booksy indexed only, 200 reviews. Needs simple mobile booking hub."
    },

    # --- CAMPAIGN 3: BIG SOCIAL / AUDITED DEFECTS ---
    {
        "id": "SOCIAL-001",
        "campaign": "3-BigSocial",
        "rank": 1,
        "business": "Guins Excavating Service (letsdig18)",
        "city": "Zebulon",
        "state": "NC",
        "industry": "Excavation contractor",
        "google_rating": 5.0,
        "reviews": 110,
        "website": "guinsexcavating.com",
        "website_status": "WEBSITE POOR - VERIFIED",
        "followers": 750000,
        "platform": "YouTube",
        "owner": "Chris Guins",
        "email": "Letsdig18@yahoo.com",
        "phone": "(919) 669-6152",
        "instagram": "@letsdig18",
        "lead_score": 90,
        "deal_value": DEFAULT_PACKAGE_ENTERPRISE,
        "pitch_hook": "Rebuilding guinsexcavating.com into a heavy equipment project showcase, commercial quote engine, and official brand hub for 750K fans.",
        "audit_notes": "750K YouTube subscribers. Website guinsexcavating.com is outdated, lacks modern project showcases, equipment gallery, and commercial quote pipeline."
    },
    {
        "id": "SOCIAL-002",
        "campaign": "3-BigSocial",
        "rank": 2,
        "business": "Firepunk Diesel",
        "city": "Plain City",
        "state": "OH",
        "industry": "Diesel performance shop",
        "google_rating": 4.8,
        "reviews": 320,
        "website": "firepunk.com",
        "website_status": "WEBSITE TERRIBLE - VERIFIED",
        "followers": 60500,
        "platform": "YouTube",
        "owner": "Lavon D. Miller",
        "email": "rick@firepunkdiesel.com",
        "phone": "(614) 733-3744",
        "instagram": "@firepunkdiesel",
        "lead_score": 89,
        "deal_value": DEFAULT_PACKAGE_ENTERPRISE,
        "pitch_hook": "Streamlining mobile parts navigation, diesel tuning appointment requests, and fixing checkout bottlenecks on firepunk.com.",
        "audit_notes": "60.5K YouTube subscribers + 144K Instagram followers. firepunk.com has serious UI/UX bottlenecks, poor mobile navigation, and underperforming parts store UX."
    },
    {
        "id": "SOCIAL-003",
        "campaign": "3-BigSocial",
        "rank": 3,
        "business": "Stiles Switch BBQ & Brew",
        "city": "Austin",
        "state": "TX",
        "industry": "Barbecue restaurant",
        "google_rating": 4.6,
        "reviews": 5821,
        "website": "stilesswitchbbq.com",
        "website_status": "WEBSITE DATED - VERIFIED",
        "followers": 124860,
        "platform": "Instagram",
        "owner": "Shane Stiles",
        "email": "catering@stilesswitchbbq.com",
        "phone": "(512) 380-9199",
        "instagram": "@stilesswitchbbq",
        "lead_score": 87,
        "deal_value": DEFAULT_PACKAGE_PRO,
        "pitch_hook": "Fixing the bare root splash page, broken 404 footer accessibility link, missing schema, and HTTP menu redirect to match their legendary reputation.",
        "audit_notes": "124.8K Instagram followers. Root domain is a bare splash page (~250 chars), page title 'Stiles Switch BBQ - Landing Page', meta description EMPTY, footer accessibility link 404s on root, zero JSON-LD schema, Holiday Shop nav points to Squarespace store with sold-out event, menu routes through plain HTTP menus.fyi redirector."
    },
    {
        "id": "SOCIAL-004",
        "campaign": "3-BigSocial",
        "rank": 4,
        "business": "Mum Foods Smokehouse & Delicatessen",
        "city": "Austin",
        "state": "TX",
        "industry": "Barbecue restaurant",
        "google_rating": 4.7,
        "reviews": 439,
        "website": "mumfoodsatx.com",
        "website_status": "WEBSITE POOR - VERIFIED",
        "followers": 23664,
        "platform": "Instagram",
        "owner": "Mum Foods Team",
        "email": "info@mumfoodsatx.com",
        "phone": "(512) 270-8021",
        "instagram": "@mumfoodsatx",
        "lead_score": 85,
        "deal_value": DEFAULT_PACKAGE_PRO,
        "pitch_hook": "Fixing the broken 404 '/deli' footer link, replacing the 515KB PDF menu with an interactive HTML menu, and resolving the conflicting market location hours.",
        "audit_notes": "23.6K Instagram followers. Audit defects: '<a href=\"/deli\">The Deli</a>' in footer nav returns HTTP 404 on every page; menu is 515KB PDF only with no HTML menu; farmers-market locations contradict between homepage and contact page; malformed schema with empty entries; /bbqanddeli reads as coming soon while footer publishes live hours."
    },
    {
        "id": "SOCIAL-005",
        "campaign": "3-BigSocial",
        "rank": 5,
        "business": "Onizuka Tattoo",
        "city": "Gardena",
        "state": "CA",
        "industry": "Tattoo studio",
        "google_rating": 4.9,
        "reviews": 43,
        "website": "onizukatattoo.com",
        "website_status": "WEBSITE DATED - VERIFIED",
        "followers": 12006,
        "platform": "Instagram",
        "owner": "Onizuka Inc",
        "email": "onizukatattoo@gmail.com",
        "phone": "(213) 626-0374",
        "instagram": "@onizukatattoo",
        "lead_score": 77,
        "deal_value": DEFAULT_PACKAGE_GROWTH,
        "pitch_hook": "Purging 2015 lorem ipsum demo blog posts, fixing the misspelled booking form button, and upgrading gallery assets to high-res HD matching your IG work.",
        "audit_notes": "12K Instagram followers. Audit defects: 3 Squarespace demo blog posts with lorem ipsum bodies still published in sitemap from 2015; booking button misspelled 'CLICK HERE: APPINTMENT FORM' pointing to external Google form; portfolio images are low-res (300-600px) compared to their IG feed; copyright stale (2024)."
    },

    # --- CAMPAIGN 3: BENCH QUALIFIED ---
    {
        "id": "BENCH-001",
        "campaign": "3-Bench",
        "rank": 6,
        "business": "Micklethwait Barbecue",
        "city": "Austin",
        "state": "TX",
        "industry": "Barbecue restaurant",
        "google_rating": 4.7,
        "reviews": 2047,
        "website": "craftmeatsaustin.com",
        "website_status": "WEBSITE ADEQUATE",
        "followers": 32318,
        "platform": "Instagram",
        "owner": "Tom Micklethwait",
        "email": "team@craftmeatsaustin.com",
        "phone": "(512) 953-3549",
        "instagram": "@craftmeats",
        "lead_score": 74,
        "deal_value": DEFAULT_PACKAGE_PRO,
        "pitch_hook": "Resolving 3 contradictory operating hours, removing suppressive 'no-follow' crawl header, and adding direct catering intake forms.",
        "audit_notes": "32.3K IG followers. Audit defects: 3 contradictory hours listed (11-9pm on homepage, 11-8pm in footer, 11-4pm on contact); x-robots-tag nofollow on every page; zero form inputs on contact/catering pages (raw mailto only); catering menu is a 2023 PDF on Google Drive."
    },
    {
        "id": "BENCH-002",
        "campaign": "3-Bench",
        "rank": 7,
        "business": "Whipped Bakery & Cafe",
        "city": "Leander/Austin",
        "state": "TX",
        "industry": "Bakery",
        "google_rating": 4.7,
        "reviews": 139,
        "website": "whippedatx.com",
        "website_status": "WEBSITE POOR - VERIFIED",
        "followers": 10695,
        "platform": "Instagram",
        "owner": "Whipped Team",
        "email": "info@whippedatx.com",
        "phone": "(512) 986-7988",
        "instagram": "@whippedatx",
        "lead_score": 78,
        "deal_value": DEFAULT_PACKAGE_GROWTH,
        "pitch_hook": "Adding the missing 2nd Austin location to the site, fixing the out-of-season Christmas menu ordering, and adding transparent pricing.",
        "audit_notes": "10.7K IG followers. Second Austin location completely missing from website; /christmas is live and orderable in late August; no prices on standard cakes list; Square buttons hardcode a single location ID."
    }
]

def validate_email(email: str) -> bool:
    if not email:
        return False
    pattern = r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"
    return bool(re.match(pattern, email.strip()))

def get_normalized_leads() -> List[Dict[str, Any]]:
    """Return cleaned, validated, and normalized lead records."""
    normalized = []
    for lead in RAW_LEADS_DATA:
        clean = dict(lead)
        clean["email_valid"] = validate_email(clean.get("email", ""))
        clean["status"] = "READY_FOR_OUTREACH"
        clean["stage"] = "UNCONTACTED"
        clean["probability"] = 0.15
        normalized.append(clean)
    return normalized

def export_raw_leads_json():
    """Saves raw leads to data/raw_leads.json."""
    out_path = DATA_DIR / "raw_leads.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(get_normalized_leads(), f, indent=2)
    print(f"Exported {len(RAW_LEADS_DATA)} leads to {out_path}")

if __name__ == "__main__":
    export_raw_leads_json()
