"""initial schema

Revision ID: c3a33ae4888b
Revises: 
Create Date: 2026-08-25 23:34:25.329874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a33ae4888b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('subject_template', sa.Text(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('followup_subject_template', sa.Text(), nullable=True),
    sa.Column('followup_body_template', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('discovered', sa.Integer(), nullable=False),
    sa.Column('leads_created', sa.Integer(), nullable=False),
    sa.Column('emails_sent', sa.Integer(), nullable=False),
    sa.Column('followups_sent', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('opened', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('positive', sa.Integer(), nullable=False),
    sa.Column('negative', sa.Integer(), nullable=False),
    sa.Column('neutral', sa.Integer(), nullable=False),
    sa.Column('unsubscribes', sa.Integer(), nullable=False),
    sa.Column('bounces', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', name='uq_daily_stat_day')
    )
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_stats_day'), ['day'], unique=False)

    op.create_table('discovery_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('area_label', sa.String(length=255), nullable=False),
    sa.Column('query', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='discoverystatus', native_enum=False), nullable=False),
    sa.Column('found_total', sa.Integer(), nullable=False),
    sa.Column('without_website', sa.Integer(), nullable=False),
    sa.Column('new_businesses', sa.Integer(), nullable=False),
    sa.Column('leads_created', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value', 'kind', name='uq_suppression')
    )
    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppressions_value'), ['value'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=96), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('has_website', sa.Boolean(), nullable=False),
    sa.Column('website_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('website_alive', sa.Boolean(), nullable=True),
    sa.Column('facebook', sa.String(length=512), nullable=True),
    sa.Column('instagram', sa.String(length=512), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('postcode', sa.String(length=32), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('timezone_name', sa.String(length=64), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('discovery_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['discovery_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_business_source')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index('ix_business_country_category', ['country_code', 'category'], unique=False)
        batch_op.create_index('ix_business_dedupe', ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_has_website'), ['has_website'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_source', sa.String(length=48), nullable=False),
    sa.Column('email_confidence', sa.Float(), nullable=False),
    sa.Column('is_role_account', sa.Boolean(), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'NEEDS_APPROVAL', 'READY', 'QUEUED', 'CONTACTED', 'FOLLOWED_UP', 'REPLIED', 'POSITIVE', 'NEUTRAL', 'NEGATIVE', 'UNSUBSCRIBED', 'BOUNCED', 'DO_NOT_CONTACT', 'FAILED', 'WON', name='leadstatus', native_enum=False), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('followups_sent', sa.Integer(), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_class', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'QUESTION', 'UNSUBSCRIBE', 'AUTO_REPLY', 'BOUNCE', 'UNKNOWN', name='replyclass', native_enum=False), nullable=True),
    sa.Column('reply_confidence', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('block_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'campaign_id', name='uq_lead_business_campaign')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('ix_lead_email', ['email'], unique=False)
        batch_op.create_index('ix_lead_status_next', ['status', 'next_action_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_unsubscribe_token'), ['unsubscribe_token'], unique=True)

    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'BOUNCED', 'SKIPPED', name='messagestatus', native_enum=False), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_messages_message_id'), ['message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_messages_status'), ['status'], unique=False)
        batch_op.create_index('ix_msg_lead_step', ['lead_id', 'step'], unique=False)
        batch_op.create_index('ix_msg_sent_at', ['sent_at'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_event_type_time', ['type', 'created_at'], unique=False)

    op.create_table('inbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('in_reply_to', sa.String(length=255), nullable=True),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('classification', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'QUESTION', 'UNSUBSCRIBE', 'AUTO_REPLY', 'BOUNCE', 'UNKNOWN', name='replyclass', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('classifier', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_messages_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_messages_from_email'), ['from_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_messages_in_reply_to'), ['in_reply_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_messages_message_id'), ['message_id'], unique=True)
        batch_op.create_index('ix_inbound_received', ['received_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_inbound_received')
        batch_op.drop_index(batch_op.f('ix_inbound_messages_message_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_messages_in_reply_to'))
        batch_op.drop_index(batch_op.f('ix_inbound_messages_from_email'))
        batch_op.drop_index(batch_op.f('ix_inbound_messages_classification'))

    op.drop_table('inbound_messages')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_type_time')

    op.drop_table('events')
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_msg_sent_at')
        batch_op.drop_index('ix_msg_lead_step')
        batch_op.drop_index(batch_op.f('ix_email_messages_status'))
        batch_op.drop_index(batch_op.f('ix_email_messages_message_id'))

    op.drop_table('email_messages')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_unsubscribe_token'))
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index('ix_lead_status_next')
        batch_op.drop_index('ix_lead_email')

    op.drop_table('leads')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_has_website'))
        batch_op.drop_index(batch_op.f('ix_businesses_country_code'))
        batch_op.drop_index('ix_business_dedupe')
        batch_op.drop_index('ix_business_country_category')

    op.drop_table('businesses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppressions_value'))

    op.drop_table('suppressions')
    op.drop_table('discovery_runs')
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_stats_day'))

    op.drop_table('daily_stats')
    op.drop_table('campaigns')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
